version: '3.8'

services:
  security-postgresql:
    image: postgres:14.5
    container_name: security-postgresql
    ports:
      - "55432:5432"  # ← host:container
    environment:
      POSTGRES_USER: secured
      POSTGRES_PASSWORD: David@2025
      POSTGRES_DB: secured
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  pgadmin-new:
    image: dpage/pgadmin4
    container_name: pgadmin-new
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - security-postgresql
    restart: always

volumes:
  pgdata:
  pgadmin_data:
